Ma3an/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("choose/role/", views.signup_role_view, name="signup_role"),
    path('signup/traveler/', views.traveler_signup_view, name='traveler_signup'),
    path('signup/agency/', views.agency_signup_view, name='agency_signup'),
    path("create/guide/", views.create_tourguide_view, name="create_tourguide_view"),
    path("profile/", views.profile_view, name="profile_view"),
    path("signin/", views.signin_view, name="signin_view"),
    path("logout/", views.log_out_view, name="log_out_view"),
]

Ma3an/accounts/templates/accounts/agency_signup.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Agency Signup{% endblock %}

{% block content %}

<div class="container py-5">
    <h2>Sign Up - Agency</h2>
    <hr>

    <form method="post">
        {% csrf_token %}

        <h4>User Information</h4>
        {{ user_form.as_p }}

        <h4>Agency Information</h4>
        {{ agency_form.as_p }}

        <button type="submit" class="btn btn-success mt-3">Sign Up</button>
    </form>

    {% if user_form.errors %}
        <div class="alert alert-danger mt-3">
            {{ user_form.errors }}
        </div>
    {% endif %}
    {% if agency_form.errors %}
        <div class="alert alert-danger mt-3">
            {{ agency_form.errors }}
        </div>
    {% endif %}
</div>


{% endblock %}

Ma3an/accounts/templates/accounts/create_tourguide.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Create Tour Guide{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Create Tour Guide</h2>

                    <form method="post" action="{% url 'accounts:create_tourguide_view' %}">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label class="form-label">Email</label>
                            <input 
                                type="email" 
                                name="email" 
                                class="form-control" 
                                placeholder="Enter email"
                                required
                            >
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Password</label>
                            <input 
                                type="password" 
                                name="password" 
                                class="form-control" 
                                placeholder="Enter password"
                                required
                            >
                        </div>

                        <div class="d-grid mt-4">
                            <button type="submit" class="btn btn-primary">
                                Create Account
                            </button>
                        </div>
                    </form>

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} mt-3">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ma3an/accounts/templates/accounts/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container py-5">
    <h2 class="mb-4">My Profile</h2>

    {% if not edit_mode %}
        <!-- عرض البيانات -->
        <p><b>Username:</b> {{ user.username }}</p>
        <p><b>Email:</b> {{ user.email }}</p>
        <p><b>First name:</b> {{ user.first_name }}</p>
        <p><b>Last name:</b> {{ user.last_name }}</p>

        <hr>

        {% if user.role == 'traveler' %}
            {% include 'accounts/partials/traveler.html' %}
        {% elif user.role == 'agency' %}
            {% include 'accounts/partials/agency.html' %}
        {% elif user.role == 'tourGuide' %}
            {% include 'accounts/partials/tourGuide.html' %}
        {% endif %}

        <a href="?edit=1" class="btn btn-primary mt-3">Edit profile</a>

    {% else %}
        <!-- editing Info -->
        <form method="post">
            {% csrf_token %}

            <h4>Account info</h4>
            <div class="mb-3">
                <label class="form-label">Username</label>
                <input name="username" value="{{ user.username }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input name="email" value="{{ user.email }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">First name</label>
                <input name="first_name" value="{{ user.first_name }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Last name</label>
                <input name="last_name" value="{{ user.last_name }}" class="form-control">
            </div>

            <hr>

            {% if user.role == 'traveler' %}
                {% include 'accounts/partials/traveler_edit.html' %}
            {% elif user.role == 'agency' %}
                {% include 'accounts/partials/agency_edit.html' %}
            {% elif user.role == 'tourGuide' %}
                {% include 'accounts/partials/tourGuide_edit.html' %}
            {% endif %}

            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% url 'accounts:profile_view' %}" class="btn btn-secondary">Cancel</a>
        </form>
    {% endif %}
</div>
{% endblock %}

Ma3an/accounts/templates/accounts/signin.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Signin{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Welcome Back!</h2>

                    <form action="{% url 'accounts:signin_view' %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="Username" name="username" required>
                        </div>

                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                        </div>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>

                    <div class="text-center mt-3">
                        <p class="mb-0">Don't have an account? 
                            <a href="{% url 'accounts:signup_role' %}">Sign Up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ma3an/accounts/templates/accounts/signup_role.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<div class="container mt-5 text-center">
    <h2>Create Account</h2>
    <p>Please choose your account type</p>

    <div class="mt-4">
        <a href="{% url 'accounts:traveler_signup' %}"
           class="btn btn-primary btn-lg m-2">
            Sign up as Traveler
        </a>

        <a href="{% url 'accounts:agency_signup' %}"
           class="btn btn-success btn-lg m-2">
            Sign up as Agency
        </a>
    </div>
</div>
{% endblock %}

Ma3an/accounts/templates/accounts/traveler_signup.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Traveler Signup{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Sign Up</h2>
                    <form action="{% url 'accounts:traveler_signup' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <input type="email" class="form-control" placeholder="Email" name="email" required>
                        </div>
                        
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="Username" name="username" required>
                        </div>
                        
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="First Name" name="first_name" required>
                        </div>
                        
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="Last Name" name="last_name" required>
                        </div>
                        
                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                        </div>
                        
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}